title: "Data project portfolio (Inder Singh)"
description: "Insights and analytics portfolio | <a href='https://linkedin.com' style='color: #fff;'>LinkedIn</a> | <a href='mailto:your-email@example.com' style='color: #fff;'>Email</a>"
theme: jekyll-theme-slate
