title: "Data Project Portfolio (Inder Singh)"
description: "Data Engineering & Analytics Projects Overview | <a href='https://www.linkedin.com/in/inder-singh-94b352234/' style='color: #0A66C2;'>LinkedIn</a> | <a href='mailto:indr.rana7@gmail.com' style='color: #00FFFF;'>Email</a>"
theme: jekyll-theme-slate
