title: "Data project portfolio (Inder Singh)"
description: "Data Engineering & Analytics Projects Overview | <a href='https://linkedin.com' style='color: #0A66C2;'>LinkedIn</a> | <a href='mailto:your-email@example.com' style='color: #00FFFF;'>Email</a>"
theme: jekyll-theme-slate
